language: generic
sudo: required
services:
  - docker

before_install:
  # since this file should be located inside the root folder the relative path's were specified
  - docker build -t conrsluk/frontend -f frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true conrsluk/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  # copied from EBS
  app: 'docker-frontend'
  # copied from EBS
  env: 'Dockerfrontend-env'
  # copied from S3
  bucket_name: 'elasticbeanstalk-eu-west-1-102064755965'
  # this is a folder inside s3 bucket, it will be created automatically with the same name as the app
  bucket_path: 'docker-frontend'
  on:
    branch: main
  # Stored inside Travis UI
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
