language: generic
sudo: required
services:
  - docker

before_install:
  # since this file should be located inside the root folder the relative path's were specified
  - docker build -t conrsluk/frontend -f frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true conrsluk/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-frontend'
  env: 'Dockerfrontend-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-102064755965'
  bucket_path: 'docker-frontend'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
