language: generic
sudo: required
services:
  - docker

before_install:
  # since this file should be located inside the root folder the relative path's were specified
  - docker build -t conrsluk/frontend -f frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true conrsluk/frontend npm run test -- --coverage
