# this file is related to complex folder, should be placed in the root of the repo for correct complex app deployment
version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      # path from the root
      context: ./complex/nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    build:
      # path from the root
      context: ./complex/server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
        # path from the root
      - ./complex/server:/home/node/app
    environment:
        # host is equal to service name above
      - REDIS_HOST=redis
      - REDIS_PORT=6379
        # host is equal to service name above
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DB=postgres
      - PG_PASSWORD=postgres
  client:
    build:
      # path from the root
      context: ./complex/client
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
        # path from the root
      - ./complex/client:/home/node/app
  worker:
    build:
      # path from the root
      context: ./complex/worker
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
        # path from the root
      - ./complex/worker:/home/node/app
    environment:
        # host is equal to service name above
      - REDIS_HOST=redis
      - REDIS_PORT=6379
