FROM node:alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json .
RUN npm install

# This step isn't needed if we use volumes
COPY --chown=node:node . .

# fix for nodemon permission issue
RUN chmod +x node_modules/.bin/nodemon

CMD ["npm","run","dev"]
